[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bash scripts/start.sh"
preDeployCommand = "bash scripts/predeploy.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
requiredMountPath = "/data"